local GlobalAddonName, E = ...
----------------------------------------------------------------
local ICON_KYRIAN = E.ICON_KYRIAN -- = 3641395
local ICON_NECROLORD = E.ICON_NECROLORD -- = 3752259 -- 3641396
local ICON_NIGHTFAE = E.ICON_NIGHTFAE -- = 3752258 -- 3641394
local ICON_VENTHYR = E.ICON_VENTHYR -- = 3257751 -- 3641397
local ICON_FISH = 1053367 -- https://www.wowhead.com/item = 133755/ (Underlight Angler)
local ICON_PVP = 1455894
----------------------------------------------------------------
E.OctoTable_Reputations_DB = {
	[2796] = {
		["AddedInPatch"] = "12.1.0.69189",
		["expansion"] = "Midnight",
		["defS"] = false,
		["ruRU"] = "Вылазки: 2-й сезон",
		["enUS"] = "Delves: Season 2",
		["deDE"] = "Tiefen: Saison 2",
		["esES"] = "Profundidades: temporada 2",
		["esMX"] = "Abismos: temporada 2",
		["frFR"] = "Gouffres saison 2",
		["itIT"] = "Scorribande: Stagione 2",
		["ptBR"] = "Imersões: Série 2",
		["koKR"] = "구렁: 2 시즌",
		["zhCN"] = "地下堡：第2赛季",
		["zhTW"] = "探究：第2賽季",
	},

	[2742] = {
		["AddedInPatch"] = "12.0.0.65390",
		["expansion"] = "Midnight",
		["defS"] = false,
		["ruRU"] = "Вылазки: 1-й сезон",
		["enUS"] = "Delves: Season 1",
		["deDE"] = "Tiefen: Saison 1",
		["esES"] = "Profundidades: temporada 1",
		["esMX"] = "Abismos: temporada 1",
		["frFR"] = "Gouffres saison 1",
		["itIT"] = "Scorribande: Stagione 1",
		["ptBR"] = "Imersões: Série 1",
		["koKR"] = "구렁: 1 시즌",
		["zhCN"] = "地下堡：第1赛季",
		["zhTW"] = "探究：第1賽季",
	},
	[2511] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Iskaara Tuskarr",
		["defS"] = false,
		["ruRU"] = "Искарские клыкарры",
		["paragonQuest"] = 66511,
		["itemCache"] = 199473,
		["icon"] = "MajorFactions_Icons_Tuskarr512",
		["expansion"] = "Dragonflight",
	},
	[2512] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Aylaag",
		["ruRU"] = "Клан Айлааг",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2513] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Ohn'ir",
		["ruRU"] = "Клан Он'ир",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[1515] = {
		["AddedInPatch"] = "6.0.1.18125",
		["enUS"] = "Arakkoa Outcasts",
		["Quartermaster"] = "85946 86037",
		["ruRU"] = "Араккоа-изгои",
		["defS"] = false,
	},
	[2517] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Wrathion",
		["ruRU"] = "Гневион",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2518] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Sabellian",
		["ruRU"] = "Сабеллиан",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[1015] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Netherwing",
		["defS"] = false,
		["ruRU"] = "Крылья Пустоты",
	},
	[2520] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Nokhud",
		["ruRU"] = "Клан Нокхуд",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2521] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Nokhud (Paragon)",
		["ruRU"] = "Клан Нокуд (идеал)",
		["expansion"] = "Dragonflight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2522] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Teerai",
		["ruRU"] = "Клан Тирай",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2523] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Dark Talons",
		["side"] = "Horde",
		["ruRU"] = "Темные Когти",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2524] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Obsidian Warders",
		["side"] = "Alliance",
		["ruRU"] = "Обсидиановые Хранители",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[1520] = {
		["AddedInPatch"] = "6.0.1.18125",
		["enUS"] = "Shadowmoon Exiles",
		["defS"] = false,
		["ruRU"] = "Изгнанники клана Призрачной Луны",
	},
	[2526] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Winterpelt Furbolg",
		["ruRU"] = "Фурболги из клана Зимней Шкуры",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[509] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "The League of Arathor",
		["side"] = "Alliance",
		["ruRU"] = "Лига Аратора",
		["defS"] = false,
	},
	[890] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Silverwing Sentinels",
		["side"] = "Alliance",
		["ruRU"] = "Среброкрылые Часовые",
		["defS"] = false,
	},
	[1269] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Golden Lotus",
		["Quartermaster"] = "59908",
		["ruRU"] = "Золотой Лотос",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[510] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "The Defilers",
		["side"] = "Horde",
		["ruRU"] = "Осквернители",
		["defS"] = false,
	},
	[1270] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Shado-Pan",
		["Quartermaster"] = "64595",
		["ruRU"] = "Шадо-Пан",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1271] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Order of the Cloud Serpent",
		["Quartermaster"] = "58414",
		["ruRU"] = "Орден Облачного Змея",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1272] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The Tillers",
		["Quartermaster"] = "58706",
		["ruRU"] = "Земледельцы",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2542] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Ukhel",
		["ruRU"] = "Клан Укхел",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2544] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Artisan's Consortium - Dragon Isles Branch",
		["ruRU"] = "Консорциум ремесленников – филиал на Драконьих островах",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[1275] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Ella",
		["ruRU"] = "Элла",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1276] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Old Hillpaw",
		["ruRU"] = "Старик Горная Лапа",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2550] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Cobalt Assembly",
		["ruRU"] = "Кобальтовая ассамблея",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2551] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Iskaara Tuskarr (Paragon)",
		["ruRU"] = "Искарские клыкарры (идеал)",
		["expansion"] = "Dragonflight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2552] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Valdrakken Accord (Paragon)",
		["ruRU"] = "Союз Вальдраккена (идеал)",
		["expansion"] = "Dragonflight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2553] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Soridormi",
		["ruRU"] = "Соридорми",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2554] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Toghus",
		["ruRU"] = "Клан Тогус",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2555] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Kaighan",
		["ruRU"] = "Клан Кейган",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[1280] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Tina Mudclaw",
		["ruRU"] = "Тина Грязный Коготь",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1281] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Gina Mudclaw",
		["ruRU"] = "Джина Грязный Коготь",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1282] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Fish Fellreed",
		["ruRU"] = "Рыба Тростниковая Шкура",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1283] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Farmer Fung",
		["ruRU"] = "Фермер Фун",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2564] = {
		["AddedInPatch"] = "10.1.0.49407",
		["enUS"] = "Loamm Niffen",
		["defS"] = false,
		["ruRU"] = "Лоаммские ниффы",
		["paragonQuest"] = 75290,
		["itemCache"] = 204712,
		["icon"] = "MajorFactions_Icons_Niffen512",
		["expansion"] = "Embers of Neltharion",
	},
	[2565] = {
		["AddedInPatch"] = "10.1.0.49407",
		["enUS"] = "Loamm Niffen (Paragon)",
		["ruRU"] = "Лоаммские ниффы (идеал)",
		["expansion"] = "Embers of Neltharion",
		["defS"] = false,
		["useless"] = "true",
	},
	[2568] = {
		["AddedInPatch"] = "10.1.0.49407",
		["enUS"] = "Glimmerogg Racer",
		["ruRU"] = "Гонщик Мерцающего Огга",
		["defS"] = false,
		["expansion"] = "Embers of Neltharion",
	},
	[2569] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The War Within",
		["ruRU"] = "The War Within",
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[2570] = {
		["itemCache"] = 225246,
		["expansion"] = "The War Within",
		["ruRU"] = "Арати Тайносводья",
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Hallowfall Arathi",
		["paragonQuest"] = 79218,
		["defS"] = false,
		["icon"] = "majorfactions_icons_flame512",
		["currency"] = 2899,
	},
	[81] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Thunder Bluff",
		["Quartermaster"] = "50483",
		["ruRU"] = "Громовой Утес",
		["defS"] = false,
		["side"] = "Horde",
	},
	[2574] = {
		["AddedInPatch"] = "10.2.0.52068",
		["enUS"] = "Dream Wardens",
		["defS"] = false,
		["ruRU"] = "Стражи Сна",
		["paragonQuest"] = 76425,
		["itemCache"] = 210992,
		["icon"] = "MajorFactions_Icons_Dream512",
		["expansion"] = "Guardians of the Dream",
	},
	[2575] = {
		["AddedInPatch"] = "10.2.0.52068",
		["enUS"] = "Dream Wardens (Paragon)",
		["ruRU"] = "Стражи Сна (идеал)",
		["expansion"] = "Guardians of the Dream",
		["defS"] = false,
		["useless"] = "true",
	},
	[1037] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Alliance Vanguard",
		["Quartermaster"] = "32773",
		["ruRU"] = "Авангард Альянса",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[1038] = {
		["AddedInPatch"] = "2.1.0",
		["enUS"] = "Ogri'la",
		["Quartermaster"] = "23428",
		["ruRU"] = "Огри'ла",
		["defS"] = false,
		["itemCurrency"] = 32569,
	},
	[2590] = {
		["itemCache"] = 225239,
		["expansion"] = "The War Within",
		["ruRU"] = "Совет Дорногала",
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Council of Dornogal",
		["paragonQuest"] = 79219,
		["defS"] = false,
		["icon"] = "majorfactions_icons_storm512",
		["currency"] = 2897,
	},
	[2593] = {
		["AddedInPatch"] = "10.2.6.53840",
		["enUS"] = "Keg Leg's Crew",
		["ruRU"] = "Команда Бочконога",
		["defS"] = false,
		["icon"] = "majorfactions_icons_plunderstorm512",
		["expansion"] = "Plunderstorm",
	},
	[2594] = {
		["itemCache"] = 225245,
		["expansion"] = "The War Within",
		["ruRU"] = "Ассамблея глубин",
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Assembly of the Deeps",
		["paragonQuest"] = 79220,
		["defS"] = false,
		["icon"] = "majorfactions_icons_candle512",
		["currency"] = 2902,
	},
	[2596] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Severed Threads (Paragon)",
		["ruRU"] = "Отрезанные нити (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[2086] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Valarjar (Paragon)",
		["ruRU"] = "Валарьяры (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[2087] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Court of Farondis (Paragon)",
		["ruRU"] = "Двор Фарондиса (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[2088] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Dreamweavers (Paragon)",
		["ruRU"] = "Ткачи Снов (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[2600] = {
		["itemCache"] = 225247,
		["expansion"] = "The War Within",
		["ruRU"] = "Отрезанные нити",
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Severed Threads",
		["paragonQuest"] = 79196,
		["defS"] = false,
		["icon"] = "majorfactions_icons_web512",
		["currency"] = 2903,
	},
	[2601] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Weaver",
		["ruRU"] = "Прядильщица",
		["paragonQuest"] = 83738,
		["itemCache"] = 226103,
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[2091] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Armies of Legionfall (Paragon)",
		["ruRU"] = "Армия погибели Легиона (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[2604] = {
		["AddedInPatch"] = "10.2.6.53840",
		["enUS"] = "Keg Leg's Crew (Paragon)",
		["ruRU"] = "Команда Бочконога (идеал)",
		["expansion"] = "Plunderstorm",
		["defS"] = false,
		["useless"] = "true",
	},
	[2605] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The General",
		["ruRU"] = "Генерал",
		["paragonQuest"] = 83739,
		["itemCache"] = 226045,
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[909] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Darkmoon Faire",
		["defS"] = false,
		["ruRU"] = "Ярмарка Новолуния",
	},
	[2607] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Vizier",
		["ruRU"] = "Визирь",
		["paragonQuest"] = 83740,
		["itemCache"] = 226100,
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[2097] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Ilyssia of the Waters",
		["ruRU"] = "Илиссия Водная",
		["defS"] = false,
		["icon"] = 1053367,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2098] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Keeper Raynae",
		["ruRU"] = "Хранительница Рейна",
		["defS"] = false,
		["icon"] = 1053367,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2099] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Akule Riverhorn",
		["ruRU"] = "Акуле Речной Рог",
		["defS"] = false,
		["icon"] = 1053367,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2611] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Hallowfall Arathi (Paragon)",
		["ruRU"] = "Арати Тайносводья (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[2612] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Council of Dornogal (Paragon)",
		["ruRU"] = "Совет Дорногала (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[2613] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Assembly of the Deeps (Paragon)",
		["ruRU"] = "Ассамблея глубин (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[2103] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Zandalari Empire",
		["side"] = "Horde",
		["ruRU"] = "Империя Зандалари",
		["paragonQuest"] = 54462,
		["itemCache"] = 166292,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2615] = {
		["AddedInPatch"] = "10.2.5.52902",
		["enUS"] = "Azerothian Archives",
		["ruRU"] = "Азеротские Архивы",
		["defS"] = false,
		["expansion"] = "Seeds of Renewal",
	},
	[529] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Argent Dawn",
		["Quartermaster"] = "11536",
		["ruRU"] = "Серебряный Рассвет",
		["defS"] = false,
	},
	[2111] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Zandalari Dinosaurs",
		["ruRU"] = "Зандаларские динозавры",
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[530] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Darkspear Trolls",
		["Quartermaster"] = "50477",
		["ruRU"] = "Племя Черного Копья",
		["defS"] = false,
		["side"] = "Horde",
	},
	[1828] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Highmountain Tribe",
		["Quartermaster"] = "106902",
		["ruRU"] = "Племена Крутогорья",
		["paragonQuest"] = 46743,
		["defS"] = false,
		["itemCache"] = 152104,
	},
	[2120] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Kul Tiras - Tiragarde",
		["side"] = "Alliance",
		["ruRU"] = "Кул-Тирас - Тирагард",
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[1064] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Taunka",
		["side"] = "Horde",
		["ruRU"] = "Таунка",
		["defS"] = false,
	},
	[2640] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Brann Bronzebeard",
		["ruRU"] = "Бранн Бронзобород",
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[1067] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Hand of Vengeance",
		["side"] = "Horde",
		["ruRU"] = "Карающая Длань",
		["defS"] = false,
	},
	[1834] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Legion",
		["defS"] = false,
		["ruRU"] = "Legion",
	},
	[1068] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Explorers' League",
		["side"] = "Alliance",
		["ruRU"] = "Лига исследователей",
		["defS"] = false,
	},
	[2644] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Delves: Season 1",
		["ruRU"] = "Вылазки: 1-й сезон",
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[2645] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "Earthen",
		["ruRU"] = "Земельники",
		["defS"] = false,
		["expansion"] = "The War Within",
	},
	[2135] = {
		["AddedInPatch"] = "7.2.5.23958",
		["enUS"] = "Chromie",
		["ruRU"] = "Хроми",
		["defS"] = false,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2647] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Vizier (Paragon)",
		["ruRU"] = "Визирь (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[2648] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The Weaver (Paragon)",
		["ruRU"] = "Прядильщица (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[2649] = {
		["AddedInPatch"] = "11.0.0.55793",
		["enUS"] = "The General (Paragon)",
		["ruRU"] = "Генерал (идеал)",
		["expansion"] = "The War Within",
		["defS"] = false,
		["useless"] = "true",
	},
	[1072] = {
		["ruRU"] = "[DNT] AC Major Faction Child Renown Test",
		["enUS"] = "[DNT] AC Major Faction Child Renown Test",
		["defS"] = false,
		["useless"] = "true",
	},
	[2653] = {
		["itemCache"] = 232463,
		["expansion"] = "Undermine(d)",
		["ruRU"] = "Картели Нижней Шахты",
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "The Cartels of Undermine",
		["paragonQuest"] = 85805,
		["defS"] = false,
		["icon"] = "majorfactions_icons_rocket512",
		["currency"] = 3118,
	},
	[2658] = {
		["itemCache"] = 230032,
		["expansion"] = "Ghosts of K'aresh",
		["ruRU"] = "Концерн К'ареша",
		["AddedInPatch"] = "11.2.0.62253",
		["enUS"] = "The K'aresh Trust",
		["paragonQuest"] = 85109,
		["defS"] = false,
		["icon"] = "majorfactions_icons_Karesh512",
		["currency"] = 3129,
	},
	[2659] = {
		["AddedInPatch"] = "11.2.0.62253",
		["enUS"] = "The K'aresh Trust (Paragon)",
		["ruRU"] = "Концерн К'ареша (идеал)",
		["expansion"] = "Ghosts of K'aresh",
		["defS"] = false,
		["useless"] = "true",
	},
	[21] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Booty Bay",
		["defS"] = false,
		["ruRU"] = "Пиратская Бухта",
	},
	[1077] = {
		["AddedInPatch"] = "BC 2.4.0",
		["enUS"] = "Shattered Sun Offensive",
		["Quartermaster"] = "25032",
		["ruRU"] = "Армия Расколотого Солнца",
		["defS"] = false,
	},
	[2662] = {
		useless = true,
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "[PH] The Power of Friendship",
		["ruRU"] = "[PH] The Power of Friendship",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2663] = {
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "Meerah",
		["ruRU"] = "Миира",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2664] = {
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "Flynn Fairwind",
		["ruRU"] = "Флинн Фэйрвинд",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2665] = {
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "Lillistrasza",
		["ruRU"] = "Лиллистраза",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2666] = {
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "Roasts and Boasts",
		["ruRU"] = "Байки за чашкой",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2667] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "The Cartels of Undermine (Paragon)",
		["ruRU"] = "Картели Нижней Шахты (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2668] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Darkfuse Solutions (Paragon)",
		["ruRU"] = "Мрачные Решалы (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2669] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Darkfuse Solutions",
		["itemCache"] = 232465,
		["ruRU"] = "Мрачные Решалы",
		["paragonQuest"] = 85808,
		["currency"] = 3177,
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[2670] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Venture Company (Paragon)",
		["ruRU"] = "Торговая компания (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2671] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Venture Company",
		["itemCache"] = 237133,
		["ruRU"] = "Торговая компания",
		["paragonQuest"] = 85810,
		["currency"] = 3176,
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[2672] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Bilgewater Cartel (Paragon)",
		["ruRU"] = "Картель Трюмных Вод (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2673] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Bilgewater Cartel",
		["itemCache"] = 237132,
		["ruRU"] = "Картель Трюмных Вод",
		["paragonQuest"] = 85806,
		["currency"] = 3169,
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[2674] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Blackwater Cartel (Paragon)",
		["ruRU"] = "Картель Черноводья (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2675] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Blackwater Cartel",
		["itemCache"] = 237135,
		["ruRU"] = "Картель Черноводья",
		["paragonQuest"] = 85807,
		["currency"] = 3171,
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[2676] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Steamwheedle Cartel (Paragon)",
		["ruRU"] = "Картель Хитрой Шестеренки (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2677] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Steamwheedle Cartel",
		["itemCache"] = 237134,
		["ruRU"] = "Картель Хитрой Шестеренки",
		["paragonQuest"] = 85809,
		["currency"] = 3173,
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[2167] = {
		["AddedInPatch"] = "7.3.0.24614",
		["enUS"] = "Argussian Reach (Paragon)",
		["ruRU"] = "Защитники Аргуса (идеал)",
		["expansion"] = "Shadows of Argus",
		["defS"] = false,
		["useless"] = "true",
	},
	[2170] = {
		["AddedInPatch"] = "7.3.0.24614",
		["enUS"] = "Argussian Reach",
		["ruRU"] = "Защитники Аргуса",
		["paragonQuest"] = 48976,
		["itemCache"] = 152922,
		["defS"] = false,
		["expansion"] = "Shadows of Argus",
	},
	[2683] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Delves: Season 2",
		["ruRU"] = "Вылазки: 2-й сезон",
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[2684] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Gallagio Loyalty Rewards Club (Paragon)",
		["ruRU"] = "Клуб лояльности Галаджио (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2685] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Gallagio Loyalty Rewards Club",
		["defS"] = false,
		["ruRU"] = "Клуб лояльности Галаджио",
		["paragonQuest"] = 85471,
		["itemCache"] = 232463,
		["icon"] = "majorfactions_icons_stars512",
		["expansion"] = "Undermine(d)",
	},
	[1345] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The Lorewalkers",
		["Quartermaster"] = "64605",
		["ruRU"] = "Хранители истории",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1090] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Kirin Tor",
		["Quartermaster"] = "32287",
		["ruRU"] = "Кирин-Тор",
		["defS"] = false,
	},
	[2688] = {
		["AddedInPatch"] = "11.1.5.60428",
		["enUS"] = "Flame's Radiance",
		["defS"] = false,
		["ruRU"] = "Сияние Пламени",
		["paragonQuest"] = 89515,
		["itemCache"] = 239489,
		["icon"] = "majorfactions_icons_Nightfall512",
		["expansion"] = "Undermine(d)",
	},
	[2689] = {
		["AddedInPatch"] = "11.1.5.60428",
		["enUS"] = "Flame's Radiance (Paragon)",
		["ruRU"] = "Сияние Пламени (идеал)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[930] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Exodar",
		["Quartermaster"] = "50306",
		["ruRU"] = "Экзодар",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[1859] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "The Nightfallen",
		["ruRU"] = "Помраченные",
		["paragonQuest"] = 46748,
		["defS"] = false,
		["itemCache"] = 152105,
	},
	[2693] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Delver's Journey (Season 1)",
		["ruRU"] = "Путь участника вылазки (1-й сезон)",
		["defS"] = false,
		["expansion"] = "Undermine(d)",
	},
	[1860] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Arcane Thirst (Thalyssra)",
		["defS"] = false,
		["ruRU"] = "Жажда магии Талисры",
	},
	[2695] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Test Account Wide Stormwind (DNT)",
		["side"] = "Alliance",
		["ruRU"] = "Test Account Wide Stormwind (DNT)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2696] = {
		["ruRU"] = "Племя Амани",
		["deDE"] = "Amanistamm",
		["koKR"] = "아마니 부족",
		["esMX"] = "Tribu amani",
		["AddedInPatch"] = "12.0.0.65390",
		["currency"] = 3354,
		["paragonQuest"] = 93566,
		["zhTW"] = "阿曼尼部族",
		["itIT"] = "Tribù Amani",
		["ptBR"] = "Tribo Amani",
		["defS"] = false,
		["enUS"] = "Amani Tribe",
		["itemCache"] = 251970,
		["icon"] = "majorfactions_icons_origin512",
		["expansion"] = "Midnight",
		["zhCN"] = "阿曼尼部族",
		["esES"] = "Tribu Amani",
		["frFR"] = "Tribu des Amani",
	},
	[2697] = {
		["AddedInPatch"] = "11.1.0.59347",
		["enUS"] = "Chase's test faction (DNT)",
		["ruRU"] = "Chase's test faction (DNT)",
		["expansion"] = "Undermine(d)",
		["defS"] = false,
		["useless"] = "true",
	},
	[1862] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Arcane Thirst (Oculeth)",
		["defS"] = false,
		["ruRU"] = "Жажда магии Окулета",
	},
	[2699] = {
		["ruRU"] = "Сингулярность",
		["deDE"] = "Die Singularität",
		["koKR"] = "특이점",
		["esMX"] = "La Singularidad",
		["AddedInPatch"] = "12.0.0.65390",
		["currency"] = 3389,
		["paragonQuest"] = 89032,
		["zhTW"] = "奇異點",
		["itIT"] = "Singolarità",
		["ptBR"] = "A Singularidade",
		["defS"] = false,
		["enUS"] = "The Singularity",
		["itemCache"] = 259334,
		["icon"] = "majorfactions_icons_sky512",
		["expansion"] = "Midnight",
		["zhCN"] = "奇点特勤",
		["esES"] = "La Singularidad",
		["frFR"] = "La Singularité",
	},
	[2700] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "DEPRECATED Fungarian Fighting Ring",
		["expansion"] = "Midnight",
		["defS"] = false,
		["useless"] = "true",
	},
	[1097] = {
		["enUS"] = "Wrath of the Lich King",
		["defS"] = false,
		["ruRU"] = "Wrath of the Lich King",
	},
	[1353] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Tushui Pandaren",
		["side"] = "Alliance",
		["ruRU"] = "Пандарены Тушуй",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1098] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Knights of the Ebon Blade",
		["Quartermaster"] = "32538",
		["ruRU"] = "Рыцари Черного Клинка",
		["defS"] = false,
	},
	[2704] = {
		["ruRU"] = "Хара'ти",
		["deDE"] = "Hara'ti",
		["koKR"] = "하라티",
		["esMX"] = "Hara'ti",
		["AddedInPatch"] = "12.0.0.65390",
		["currency"] = 3370,
		["paragonQuest"] = 89035,
		["zhTW"] = "哈拉提",
		["itIT"] = "Hara'ti",
		["ptBR"] = "Hara'ti",
		["defS"] = false,
		["enUS"] = "Hara'ti",
		["itemCache"] = 256055,
		["icon"] = "majorfactions_icons_root512",
		["expansion"] = "Midnight",
		["zhCN"] = "哈籁提",
		["esES"] = "Hara'ti",
		["frFR"] = "Hara’ti",
	},
	[2705] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Amani Tribe (Paragon)",
		["ruRU"] = "Племя Амани (идеал)",
		["expansion"] = "Midnight",
		["defS"] = false,
		["useless"] = "true",
	},
	[934] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Scryers",
		["Quartermaster"] = "19331",
		["ruRU"] = "Провидцы",
		["defS"] = false,
		["itemCurrency"] = 29736,
	},
	[2710] = {
		["ruRU"] = "Двор Луносвета",
		["deDE"] = "Hof in Silbermond",
		["koKR"] = "실버문 궁정",
		["esMX"] = "Corte de Lunargenta",
		["AddedInPatch"] = "12.0.0.65390",
		["currency"] = 3365,
		["paragonQuest"] = 93811,
		["zhTW"] = "銀月城宮廷",
		["itIT"] = "Corte di Lunargenta",
		["ptBR"] = "Corte de Luaprata",
		["defS"] = false,
		["enUS"] = "Silvermoon Court",
		["itemCache"] = 263433,
		["icon"] = "majorfactions_icons_light512",
		["expansion"] = "Midnight",
		["zhCN"] = "银月宫廷",
		["esES"] = "Corte de Lunargenta",
		["frFR"] = "Cour de Lune-d’Argent",
	},
	[2711] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Magisters",
		["ruRU"] = "Магистры",
		["defS"] = false,
		["expansion"] = "Midnight",
	},
	[2712] = {
		["itIT"] = "Cavalieri del Sangue",
		["ptBR"] = "Cavaleiros Sangrentos",
		["ruRU"] = "Рыцари крови",
		["deDE"] = "Blutritter",
		["koKR"] = "혈기사",
		["esMX"] = "Caballeros de sangre",
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Blood Knights",
		["defS"] = false,
		["expansion"] = "Midnight",
		["zhTW"] = "血騎士",
		["zhCN"] = "血骑士",
		["esES"] = "Caballeros de sangre",
		["frFR"] = "Chevaliers de sang",
	},
	[2713] = {
		["itIT"] = "Lungopasso",
		["ptBR"] = "Andarilhos",
		["ruRU"] = "Странники",
		["deDE"] = "Weltenwanderer",
		["koKR"] = "원정순찰대",
		["esMX"] = "Los Errantes",
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Farstriders",
		["defS"] = false,
		["expansion"] = "Midnight",
		["zhTW"] = "遠行者",
		["zhCN"] = "远行者",
		["esES"] = "Errantes",
		["frFR"] = "Pérégrins",
	},
	[2714] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Shades of the Row",
		["ruRU"] = "Тени Закоулка",
		["defS"] = false,
		["expansion"] = "Midnight",
	},
	[1104] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Frenzyheart Tribe",
		["Quartermaster"] = "31911",
		["ruRU"] = "Племя Бешеного Сердца",
		["defS"] = false,
	},
	[1105] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Oracles",
		["Quartermaster"] = "31910",
		["ruRU"] = "Оракулы",
		["defS"] = false,
	},
	[469] = {
		useless = true,
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Alliance",
		["side"] = "Alliance",
		["ruRU"] = "Альянс",
		["defS"] = nil,
	},
	[1106] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Argent Crusade",
		["Quartermaster"] = "30431",
		["ruRU"] = "Серебряный Авангард",
		["defS"] = false,
	},
	[2722] = {
		["AddedInPatch"] = "11.2.0.62253",
		["enUS"] = "Delves: Season 3",
		["ruRU"] = "Вылазки: 3-й сезон",
		["defS"] = false,
		["expansion"] = "Ghosts of K'aresh",
	},
	[2725] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "The Singularity (Paragon)",
		["ruRU"] = "Сингулярность (идеал)",
		["expansion"] = "Midnight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2726] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Hara'ti (Paragon)",
		["ruRU"] = "Хара'ти (идеал)",
		["expansion"] = "Midnight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2727] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Silvermoon Court (Paragon)",
		["ruRU"] = "Двор Луносвета (идеал)",
		["expansion"] = "Midnight",
		["defS"] = false,
		["useless"] = "true",
	},
	[59] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Thorium Brotherhood",
		["defS"] = false,
		["ruRU"] = "Братство Тория",
	},
	[70] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Syndicate",
		["defS"] = false,
		["ruRU"] = "Синдикат",
	},
	[941] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Mag'har",
		["Quartermaster"] = "20241",
		["ruRU"] = "Маг'хары",
		["defS"] = false,
		["side"] = "Horde",
	},
	[2736] = {
		["AddedInPatch"] = "11.2.0.62253",
		["enUS"] = "Manaforge Vandals",
		["ruRU"] = "Крушители манагорнов",
		["defS"] = false,
		["icon"] = "majorfactions_icons_ManaforgeVandals512",
		["expansion"] = "Ghosts of K'aresh",
	},
	[942] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Cenarion Expedition",
		["Quartermaster"] = "17904",
		["ruRU"] = "Кенарийская экспедиция",
		["defS"] = false,
	},
	[2739] = {
		["AddedInPatch"] = "11.2.0.62253",
		["enUS"] = "Delves: Coffer Key Shards Conversion",
		["ruRU"] = "Вылазки: обмен осколков ключа от сундука",
		["defS"] = false,
		["expansion"] = "Ghosts of K'aresh",
	},
	[1883] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Dreamweavers",
		["ruRU"] = "Ткачи Снов",
		["paragonQuest"] = 46747,
		["defS"] = false,
		["itemCache"] = 152103,
	},
	[1117] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Sholazar Basin",
		["defS"] = false,
		["ruRU"] = "Низина Шолазар",
	},
	[1118] = {
		["enUS"] = "Classic",
		["defS"] = false,
		["ruRU"] = "World of Warcraft",
	},
	[2744] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Valeera Sanguinar",
		["ruRU"] = "Валира Сангвинар",
		["defS"] = false,
		["expansion"] = "Midnight",
	},
	[1119] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Sons of Hodir",
		["Quartermaster"] = "32540",
		["ruRU"] = "Сыны Ходира",
		["defS"] = false,
	},
	[1375] = {
		["AddedInPatch"] = "5.1.0.16309",
		["enUS"] = "Dominance Offensive",
		["Quartermaster"] = "69060",
		["ruRU"] = "Армия Покорителей",
		["side"] = "Horde",
		["defS"] = false,
		["expansion"] = "Landfall",
	},
	[1376] = {
		["AddedInPatch"] = "5.1.0.16309",
		["enUS"] = "Operation: Shieldwall",
		["Quartermaster"] = "69059",
		["ruRU"] = "Операция \"Заслон\"",
		["side"] = "Alliance",
		["defS"] = false,
		["expansion"] = "Landfall",
	},
	[1888] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Jandvik Vrykul",
		["defS"] = false,
		["ruRU"] = "Яндвикские врайкулы",
	},
	[946] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Honor Hold",
		["Quartermaster"] = "17657",
		["ruRU"] = "Оплот Чести",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[1124] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Sunreavers",
		["Quartermaster"] = "34772",
		["ruRU"] = "Похитители Солнца",
		["defS"] = false,
		["side"] = "Horde",
	},
	[947] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Thrallmar",
		["Quartermaster"] = "17585",
		["ruRU"] = "Траллмар",
		["defS"] = false,
		["side"] = "Horde",
	},
	[1126] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Frostborn",
		["side"] = "Alliance",
		["ruRU"] = "Зиморожденные",
		["defS"] = false,
	},
	[1894] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "The Wardens",
		["ruRU"] = "Стражи",
		["paragonQuest"] = 46749,
		["defS"] = false,
		["itemCache"] = 152107,
	},
	[2764] = {
		["itIT"] = "Preda: Stagione 1",
		["ptBR"] = "Presa: Temporada 1",
		["ruRU"] = "Охота: 1-й сезон",
		["deDE"] = "Beutejagd: Saison 1",
		["koKR"] = "사냥감: 1 시즌",
		["esMX"] = "Presa: temporada 1",
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Prey: Season 1",
		["defS"] = false,
		["expansion"] = "Midnight",
		["zhTW"] = "狩獵：第1賽季",
		["zhCN"] = "狩猎：第1赛季",
		["esES"] = "Presa: temporada 1",
		["frFR"] = "Traque saison 1",
	},
	[2766] = {
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "Brawl'gar Arena",
		["side"] = "Horde",
		["ruRU"] = "Арена \"Морд'Бой\"",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2767] = {
		["AddedInPatch"] = "11.2.7.64587",
		["enUS"] = "Bizmo's Brawlpub",
		["side"] = "Alliance",
		["ruRU"] = "Потасовочная \"У Бизмо\"",
		["defS"] = false,
		["expansion"] = "Midnight Prologue: The Warning",
	},
	[2770] = {
		["itIT"] = "Duello del Carnefice",
		["ptBR"] = "Duellum do Matador",
		["defS"] = false,
		["ruRU"] = "Дуэлянты Зубца убийцы",
		["zhTW"] = "殺戮者決鬥會",
		["deDE"] = "Schlächterduellum",
		["koKR"] = "학살자의 결전장",
		["esMX"] = "Duelario del Asesino",
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Slayer's Duellum",
		["itemCache"] = 267299,
		["expansion"] = "Midnight",
		["paragonQuest"] = 94492,
		["zhCN"] = "屠戮角斗",
		["esES"] = "Duellum del Asesino",
		["frFR"] = "Duellum meurtrier",
	},
	[1899] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Moonguard",
		["defS"] = false,
		["ruRU"] = "Лунные стражи",
	},
	[1133] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Bilgewater Cartel",
		["Quartermaster"] = "50323",
		["ruRU"] = "Картель Трюмных Вод",
		["side"] = "Horde",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[2774] = {
		["AddedInPatch"] = "12.0.0.65390",
		["enUS"] = "Slayer's Duellum (Paragon)",
		["ruRU"] = "Дуэлянты Зубца убийцы (идеал)",
		["expansion"] = "Midnight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2264] = {
		["AddedInPatch"] = "8.0.1.27326",
		["enUS"] = "Kul Tiras - Drustvar",
		["ruRU"] = "Кул-Тирас - Друствар",
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2265] = {
		["AddedInPatch"] = "8.0.1.27326",
		["enUS"] = "Kul Tiras - Stormsong",
		["ruRU"] = "Кул-Тирас - долина Штормов",
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[1135] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "The Earthen Ring",
		["Quartermaster"] = "50324",
		["ruRU"] = "Служители Земли",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[349] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Ravenholdt",
		["defS"] = false,
		["ruRU"] = "Черный Ворон",
	},
	[2792] = {
		["ruRU"] = "Места проведения ритуалов",
		["deDE"] = "Ritualstätten",
		["koKR"] = "의식 지점",
		["esMX"] = "Sitios de ritual",
		["AddedInPatch"] = "12.0.5.67088",
		["paragonQuest"] = 95391,
		["zhTW"] = "儀式地點",
		["itIT"] = "Siti Rituali",
		["ptBR"] = "Sítios Ritualísticos",
		["defS"] = false,
		["enUS"] = "Ritual Sites",
		["itemCache"] = 269234,
		["icon"] = "majorfactions_icons_RitualSites512",
		["expansion"] = "Midnight",
		["zhCN"] = "仪式场地",
		["esES"] = "Lugares de ritual",
		["frFR"] = "Sites rituels",
	},
	[72] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Stormwind",
		["Quartermaster"] = "49877",
		["ruRU"] = "Штормград",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[47] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Ironforge",
		["Quartermaster"] = "50309",
		["ruRU"] = "Стальгорн",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[54] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Gnomeregan",
		["Quartermaster"] = "50308",
		["ruRU"] = "Гномреган",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[67] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Horde",
		["side"] = "Horde",
		["ruRU"] = "Орда",
		["defS"] = false,
	},
	[68] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Undercity",
		["Quartermaster"] = "50304",
		["ruRU"] = "Подгород",
		["defS"] = false,
		["side"] = "Horde",
	},
	[69] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Darnassus",
		["Quartermaster"] = "50305",
		["ruRU"] = "Дарнас",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[1444] = {
		["AddedInPatch"] = "6.0.1.18125",
		["enUS"] = "Warlords of Draenor",
		["defS"] = false,
		["ruRU"] = "Warlords of Draenor",
	},
	[576] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Timbermaw Hold",
		["defS"] = false,
		["ruRU"] = "Древобрюхи",
	},
	[87] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Bloodsail Buccaneers",
		["defS"] = false,
		["ruRU"] = "Пираты Кровавого Паруса",
	},
	[92] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Gelkis Clan Centaur",
		["defS"] = false,
		["ruRU"] = "Кентавры из племени Гелкис",
	},
	[93] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Magram Clan Centaur",
		["defS"] = false,
		["ruRU"] = "Кентавры из племени Маграм",
	},
	[577] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Everlook",
		["defS"] = false,
		["ruRU"] = "Круговзор",
	},
	[1919] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Arcane Thirst (Valtrois)",
		["defS"] = false,
		["ruRU"] = "Жажда магии Вальтруа",
	},
	[169] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Steamwheedle Cartel",
		["defS"] = false,
		["ruRU"] = "Картель Хитрой Шестеренки",
	},
	[270] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Zandalar Tribe",
		["defS"] = false,
		["ruRU"] = "Племя Зандалари",
	},
	[1736] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Tormmok",
		["defS"] = false,
		["ruRU"] = "Тормок",
	},
	[470] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Ratchet",
		["defS"] = false,
		["ruRU"] = "Кабестан",
	},
	[1091] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Wyrmrest Accord",
		["Quartermaster"] = "32533",
		["ruRU"] = "Драконий союз",
		["defS"] = false,
	},
	[609] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Cenarion Circle",
		["defS"] = false,
		["ruRU"] = "Круг Кенария",
	},
	[1156] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Ashen Verdict",
		["Quartermaster"] = "37687",
		["ruRU"] = "Пепельный союз",
		["defS"] = false,
	},
	[729] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Frostwolf Clan",
		["side"] = "Horde",
		["ruRU"] = "Азеротский клан Северного Волка",
		["defS"] = false,
	},
	[730] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Stormpike Guard",
		["side"] = "Alliance",
		["ruRU"] = "Стража Грозовой Вершины",
		["defS"] = false,
	},
	[1984] = {
		["AddedInPatch"] = "7.0.3.21570",
		["enUS"] = "The First Responders",
		["ruRU"] = "Спасатели",
		["defS"] = false,
		["expansion"] = "Legion",
	},
	[1158] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Guardians of Hyjal",
		["Quartermaster"] = "50314",
		["ruRU"] = "Стражи Хиджала",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[809] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Shen'dralar",
		["defS"] = false,
		["ruRU"] = "Шен'дралар",
	},
	[889] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Warsong Outriders",
		["side"] = "Horde",
		["ruRU"] = "Всадники Песни Войны",
		["defS"] = false,
	},
	[891] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Alliance Forces",
		["side"] = "Alliance",
		["ruRU"] = "Силы Альянса",
		["defS"] = false,
	},
	[892] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Horde Forces",
		["side"] = "Horde",
		["ruRU"] = "Силы Орды",
		["defS"] = false,
	},
	[910] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Brood of Nozdormu",
		["defS"] = false,
		["ruRU"] = "Род Ноздорму",
	},
	[911] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Silvermoon City",
		["Quartermaster"] = "50484",
		["ruRU"] = "Луносвет",
		["defS"] = false,
		["side"] = "Horde",
	},
	[922] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Tranquillien",
		["Quartermaster"] = "16528",
		["ruRU"] = "Транквиллион",
		["defS"] = false,
		["side"] = "Horde",
	},
	[1162] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Cataclysm",
		["ruRU"] = "Cataclysm",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[932] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Aldor",
		["Quartermaster"] = "19321",
		["ruRU"] = "Алдоры",
		["defS"] = false,
		["itemCurrency"] = 29735,
	},
	[933] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Consortium",
		["Quartermaster"] = "20242",
		["ruRU"] = "Консорциум",
		["defS"] = false,
	},
	[1419] = {
		["AddedInPatch"] = "5.1.0.16309",
		["enUS"] = "Bizmo's Brawlpub (Season 1)",
		["side"] = "Alliance",
		["ruRU"] = "Потасовочная \"У Бизмо\" (сезон 1)",
		["defS"] = false,
		["expansion"] = "Landfall",
	},
	[935] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Sha'tar",
		["Quartermaster"] = "21432",
		["ruRU"] = "Ша'тар",
		["defS"] = false,
	},
	[936] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Shattrath City",
		["defS"] = false,
		["ruRU"] = "Город Шаттрат",
	},
	[948] = {
		["enUS"] = "Test Faction 2",
		["defS"] = false,
		["ruRU"] = "Тестовая фракция 2",
	},
	[967] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Violet Eye",
		["defS"] = false,
		["ruRU"] = "Аметистовое Око",
	},
	[949] = {
		["enUS"] = "Test Faction 1",
		["defS"] = false,
		["ruRU"] = "Тестовая фракция 1",
	},
	[1012] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Ashtongue Deathsworn",
		["Quartermaster"] = "23159",
		["ruRU"] = "Пеплоусты-служители",
		["defS"] = false,
	},
	[978] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Kurenai",
		["Quartermaster"] = "20240",
		["ruRU"] = "Куренай",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[980] = {
		["enUS"] = "The Burning Crusade",
		["defS"] = false,
		["ruRU"] = "The Burning Crusade",
	},
	[1168] = {
		["AddedInPatch"] = "4.0.0",
		["enUS"] = "Guild",
		["defS"] = false,
		["ruRU"] = "Гильдия",
	},
	[989] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Keepers of Time",
		["Quartermaster"] = "21643",
		["ruRU"] = "Хранители Времени",
		["defS"] = false,
	},
	[1169] = {
		["AddedInPatch"] = "4.0.0",
		["enUS"] = "Guild",
		["defS"] = false,
		["ruRU"] = "Гильдия",
	},
	[1445] = {
		["AddedInPatch"] = "6.0.1.18125",
		["enUS"] = "Frostwolf Orcs",
		["Quartermaster"] = "86036",
		["ruRU"] = "Клан Северного Волка",
		["defS"] = false,
		["side"] = "Horde",
	},
	[1681] = {
		["AddedInPatch"] = "6.0.1.18443",
		["enUS"] = "Vol'jin's Spear",
		["Quartermaster"] = "85115",
		["ruRU"] = "Копье Вол'джина",
		["defS"] = false,
		["side"] = "Horde",
	},
	[1011] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Lower City",
		["Quartermaster"] = "21655",
		["ruRU"] = "Нижний Город",
		["defS"] = false,
	},
	[1682] = {
		["AddedInPatch"] = "6.0.1.18443",
		["enUS"] = "Wrynn's Vanguard",
		["Quartermaster"] = "80882",
		["ruRU"] = "Авангард Ринна",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[970] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Sporeggar",
		["Quartermaster"] = "18382",
		["ruRU"] = "Спореггар",
		["defS"] = false,
		["itemCurrency"] = 24245,
	},
	[1172] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Dragonmaw Clan",
		["Quartermaster"] = "49387",
		["ruRU"] = "Клан Драконьей Пасти",
		["side"] = "Horde",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1031] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "Sha'tari Skyguard",
		["Quartermaster"] = "23367",
		["ruRU"] = "Стражи небес Ша'тар",
		["defS"] = false,
	},
	[1173] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Ramkahen",
		["Quartermaster"] = "48617",
		["ruRU"] = "Рамкахены",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1050] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Valiance Expedition",
		["side"] = "Alliance",
		["ruRU"] = "Экспедиция Отважных",
		["defS"] = false,
	},
	[1174] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Wildhammer Clan",
		["Quartermaster"] = "49386",
		["ruRU"] = "Клан Громового Молота",
		["side"] = "Alliance",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1052] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Horde Expedition",
		["Quartermaster"] = "32565 32774",
		["ruRU"] = "Экспедиция Орды",
		["defS"] = false,
		["side"] = "Horde",
	},
	[1073] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Kalu'ak",
		["Quartermaster"] = "32763",
		["ruRU"] = "Калу'ак",
		["defS"] = false,
	},
	[1085] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "Warsong Offensive",
		["side"] = "Horde",
		["ruRU"] = "Армия Песни Войны",
		["defS"] = false,
	},
	[589] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Wintersaber Trainers",
		["side"] = "Alliance",
		["ruRU"] = "Укротители ледопардов",
		["defS"] = false,
	},
	[1094] = {
		["AddedInPatch"] = "3.0.1",
		["enUS"] = "The Silver Covenant",
		["Quartermaster"] = "34881",
		["ruRU"] = "Серебряный Союз",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[1177] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Baradin's Wardens",
		["Quartermaster"] = "47328",
		["ruRU"] = "Защитники Тол Барада",
		["side"] = "Alliance",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1134] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Gilneas",
		["Quartermaster"] = "50307",
		["ruRU"] = "Гилнеас",
		["side"] = "Alliance",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1178] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Hellscream's Reach",
		["Quartermaster"] = "48531",
		["ruRU"] = "Батальон Адского Крика",
		["side"] = "Horde",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1171] = {
		["AddedInPatch"] = "4.0.3",
		["enUS"] = "Therazane",
		["Quartermaster"] = "45408",
		["ruRU"] = "Теразан",
		["defS"] = false,
		["expansion"] = "The Shattering",
	},
	[1690] = {
		["AddedInPatch"] = "6.0.1.18522",
		["enUS"] = "Brawl'gar Arena (Season 2)",
		["side"] = "Horde",
		["ruRU"] = "Арена \"Морд'Бой\" (сезон 2)",
		["defS"] = false,
	},
	[1435] = {
		["AddedInPatch"] = "5.2.0.16486",
		["enUS"] = "Shado-Pan Assault",
		["Quartermaster"] = "70346",
		["ruRU"] = "Натиск Шадо-Пан",
		["defS"] = false,
		["expansion"] = "The Thunder King",
	},
	[1691] = {
		["AddedInPatch"] = "6.0.1.18522",
		["enUS"] = "Bizmo's Brawlpub (Season 2)",
		["side"] = "Alliance",
		["ruRU"] = "Потасовочная \"У Бизмо\" (сезон 2)",
		["defS"] = false,
	},
	[1947] = {
		["AddedInPatch"] = "7.0.1.20914",
		["enUS"] = "Illidari",
		["defS"] = false,
		["ruRU"] = "Иллидари",
	},
	[1357] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Nomi",
		["ruRU"] = "Номи",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1948] = {
		["AddedInPatch"] = "7.0.1.20914",
		["enUS"] = "Valarjar",
		["ruRU"] = "Валарьяры",
		["paragonQuest"] = 46746,
		["defS"] = false,
		["itemCache"] = 152106,
	},
	[1735] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Barracks Bodyguards",
		["defS"] = false,
		["ruRU"] = "Телохранители из казарм",
	},
	[1228] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Forest Hozen",
		["side"] = "Horde",
		["ruRU"] = "Лесные хозены",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1989] = {
		["AddedInPatch"] = "7.0.3.21691",
		["enUS"] = "Moon Guard",
		["ruRU"] = "Лунные стражи",
		["defS"] = false,
		["expansion"] = "Legion",
	},
	[2085] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Highmountain Tribe (Paragon)",
		["ruRU"] = "Племена Крутогорья (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[1273] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Jogu the Drunk",
		["ruRU"] = "Йогу Пьяный",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1440] = {
		["AddedInPatch"] = "5.3.0.16844",
		["enUS"] = "Darkspear Rebellion",
		["ruRU"] = "Восстание Черного Копья",
		["defS"] = false,
		["expansion"] = "Escalation",
	},
	[1277] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Chee Chee",
		["ruRU"] = "Чи-Чи",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1278] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Sho",
		["ruRU"] = "Шо",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1279] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Haohan Mudclaw",
		["ruRU"] = "Хаохань Грязный Коготь",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1302] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The Anglers",
		["Quartermaster"] = "63721",
		["ruRU"] = "Рыболовы",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2370] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Dino Training - Direhorn",
		["side"] = "Horde",
		["ruRU"] = "Обучение динозавров – Дикорог",
		["defS"] = false,
		["expansion"] = "Tides of Vengeance",
	},
	[2371] = {
		["AddedInPatch"] = "8.1.5.29701",
		["enUS"] = "Bizmo's Brawlpub (Season 4)",
		["side"] = "Alliance",
		["ruRU"] = "Потасовочная \"У Бизмо\" (4-й сезон)",
		["defS"] = false,
		["expansion"] = "Tides of Vengeance",
	},
	[2372] = {
		["AddedInPatch"] = "8.1.5.29701",
		["enUS"] = "Brawl'gar Arena (Season 4)",
		["side"] = "Horde",
		["ruRU"] = "Арена \"Морд'Бой\" (4-й сезон)",
		["defS"] = false,
		["expansion"] = "Tides of Vengeance",
	},
	[2373] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "The Unshackled",
		["side"] = "Horde",
		["ruRU"] = "Освобожденные",
		["paragonQuest"] = 53982,
		["itemCache"] = 169940,
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2374] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "The Unshackled (Paragon)",
		["ruRU"] = "Освобожденные (идеал)",
		["expansion"] = "Rise of Azshara",
		["defS"] = false,
		["useless"] = "true",
	},
	[2375] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Hunter Akana",
		["side"] = "Alliance",
		["ruRU"] = "Мастер охоты Акана",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2376] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Farseer Ori",
		["side"] = "Alliance",
		["ruRU"] = "Оракул Ори",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2377] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Bladesman Inowari",
		["side"] = "Alliance",
		["ruRU"] = "Мастер клинка Иновари",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2378] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Zandalari Empire (Paragon)",
		["ruRU"] = "Империя Зандалари (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2379] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Proudmoore Admiralty (Paragon)",
		["ruRU"] = "Адмиралтейство Праудмуров (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2380] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Talanji's Expedition (Paragon)",
		["ruRU"] = "Экспедиция Таланджи (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2381] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Storm's Wake (Paragon)",
		["ruRU"] = "Орден Возрождения Шторма (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2382] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Voldunai (Paragon)",
		["ruRU"] = "Жители Вол'дуна (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2383] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Order of Embers (Paragon)",
		["ruRU"] = "Орден Пылающих Углей (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2384] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "7th Legion (Paragon)",
		["ruRU"] = "7-й легион (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2385] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "The Honorbound (Paragon)",
		["ruRU"] = "Армия Чести (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2386] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Champions of Azeroth (Paragon)",
		["ruRU"] = "Защитники Азерот (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2387] = {
		["AddedInPatch"] = "8.1.0.28724",
		["enUS"] = "Tortollan Seekers (Paragon)",
		["ruRU"] = "Тортолланские искатели (идеал)",
		["expansion"] = "Tides of Vengeance",
		["defS"] = false,
		["useless"] = "true",
	},
	[2388] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Poen Gillbrack",
		["side"] = "Horde",
		["ruRU"] = "Поэн Солежабрик",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2389] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Neri Sharpfin",
		["side"] = "Horde",
		["ruRU"] = "Нери Остроерш",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2390] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Vim Brineheart",
		["side"] = "Horde",
		["ruRU"] = "Вим Соленодух",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2391] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Rustbolt Resistance",
		["ruRU"] = "Ржавоболтское сопротивление",
		["paragonQuest"] = 55348,
		["itemCache"] = 170061,
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2392] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Rustbolt Resistance (Paragon)",
		["ruRU"] = "Ржавоболтское сопротивление (идеал)",
		["expansion"] = "Rise of Azshara",
		["defS"] = false,
		["useless"] = "true",
	},
	[1337] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The Klaxxi",
		["Quartermaster"] = "64599",
		["ruRU"] = "Клакси",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1710] = {
		["AddedInPatch"] = "6.0.1.18566",
		["enUS"] = "Sha'tari Defense",
		["Quartermaster"] = "85427",
		["ruRU"] = "Защитники Ша'тар",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[2395] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Honeyback Hive",
		["side"] = "Alliance",
		["ruRU"] = "Улей Медокрылов",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2396] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Honeyback Drone",
		["side"] = "Alliance",
		["ruRU"] = "Трутень из улья Медокрылов",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2397] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Honeyback Hivemother",
		["side"] = "Alliance",
		["ruRU"] = "Пчеломатка улья Медокрылов",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2398] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Honeyback Harvester",
		["side"] = "Alliance",
		["ruRU"] = "Фуражир из улья Медокрылов",
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[1341] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The August Celestials",
		["Quartermaster"] = "64032 64001",
		["ruRU"] = "Небожители",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2400] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Waveblade Ankoan",
		["side"] = "Alliance",
		["ruRU"] = "Клинки Волн",
		["paragonQuest"] = 55976,
		["itemCache"] = 169939,
		["defS"] = false,
		["expansion"] = "Rise of Azshara",
	},
	[2401] = {
		["AddedInPatch"] = "8.2.0.30918",
		["enUS"] = "Waveblade Ankoan (Paragon)",
		["ruRU"] = "Анкоа из клана Клинков Волн (идеал)",
		["expansion"] = "Rise of Azshara",
		["defS"] = false,
		["useless"] = "true",
	},
	[1351] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The Brewmasters",
		["ruRU"] = "Хмелевары",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1352] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Huojin Pandaren",
		["side"] = "Horde",
		["ruRU"] = "Пандарены Хоцзинь",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1204] = {
		["AddedInPatch"] = "4.2.0",
		["enUS"] = "Avengers of Hyjal",
		["Quartermaster"] = "54401",
		["ruRU"] = "Хиджальские мстители",
		["defS"] = false,
		["expansion"] = "Rage of the Firelands",
	},
	[1358] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Nat Pagle",
		["ruRU"] = "Нат Пэгл",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[1359] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "The Black Prince",
		["ruRU"] = "Черный принц",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2407] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Ascended",
		["ruRU"] = "Перерожденные",
		["paragonQuest"] = 61097,
		["defS"] = false,
		["icon"] = "CovenantChoice-Panel-Sigil-Kyrian",
		["itemCache"] = 180647,
	},
	[1374] = {
		["AddedInPatch"] = "5.1.0.16309",
		["enUS"] = "Brawl'gar Arena (Season 1)",
		["side"] = "Horde",
		["ruRU"] = "Арена \"Морд'Бой\" (сезон 1)",
		["defS"] = false,
		["expansion"] = "Landfall",
	},
	[1387] = {
		["AddedInPatch"] = "5.2.0.16408",
		["enUS"] = "Kirin Tor Offensive",
		["Quartermaster"] = "68000",
		["ruRU"] = "Армия Кирин-Тора",
		["side"] = "Alliance",
		["defS"] = false,
		["expansion"] = "The Thunder King",
	},
	[2410] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Undying Army",
		["ruRU"] = "Неумирающая армия",
		["paragonQuest"] = 61095,
		["defS"] = false,
		["icon"] = "CovenantChoice-Panel-Sigil-Necrolords",
		["itemCache"] = 180646,
	},
	[1388] = {
		["AddedInPatch"] = "5.2.0.16408",
		["enUS"] = "Sunreaver Onslaught",
		["Quartermaster"] = "67672",
		["ruRU"] = "Войска Похитителей Солнца",
		["side"] = "Horde",
		["defS"] = false,
		["expansion"] = "The Thunder King",
	},
	[76] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Orgrimmar",
		["Quartermaster"] = "50488",
		["ruRU"] = "Оргриммар",
		["defS"] = false,
		["side"] = "Horde",
	},
	[2413] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Court of Harvesters",
		["ruRU"] = "Двор Жнецов",
		["paragonQuest"] = 61100,
		["defS"] = false,
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["itemCache"] = 180648,
	},
	[2414] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Shadowlands",
		["defS"] = false,
		["ruRU"] = "Темные Земли",
	},
	[2415] = {
		["AddedInPatch"] = "8.3.0.33062",
		["enUS"] = "Rajani",
		["ruRU"] = "Раджани",
		["paragonQuest"] = 58096,
		["itemCache"] = 174483,
		["defS"] = false,
		["expansion"] = "Visions of N'Zoth",
	},
	[2416] = {
		["AddedInPatch"] = "8.3.0.33062",
		["enUS"] = "Rajani (Paragon)",
		["ruRU"] = "Раджани (идеал)",
		["expansion"] = "Visions of N'Zoth",
		["defS"] = false,
		["useless"] = "true",
	},
	[2417] = {
		["AddedInPatch"] = "8.3.0.33062",
		["enUS"] = "Uldum Accord",
		["ruRU"] = "Ульдумский союз",
		["paragonQuest"] = 58097,
		["itemCache"] = 174484,
		["defS"] = false,
		["expansion"] = "Visions of N'Zoth",
	},
	[2418] = {
		["AddedInPatch"] = "8.3.0.33062",
		["enUS"] = "Uldum Accord (Paragon)",
		["ruRU"] = "Ульдумский союз (идеал)",
		["expansion"] = "Visions of N'Zoth",
		["defS"] = false,
		["useless"] = "true",
	},
	[990] = {
		["AddedInPatch"] = "2.0.1",
		["enUS"] = "The Scale of the Sands",
		["defS"] = false,
		["ruRU"] = "Песчаная Чешуя",
	},
	[1492] = {
		["AddedInPatch"] = "5.4.0.17169",
		["enUS"] = "Emperor Shaohao",
		["ruRU"] = "Император Шаохао",
		["defS"] = false,
		["expansion"] = "Siege of Orgrimmar",
	},
	[1708] = {
		["AddedInPatch"] = "6.0.1.18566",
		["enUS"] = "Laughing Skull Orcs",
		["Quartermaster"] = "86698",
		["ruRU"] = "Клан Веселого Черепа",
		["defS"] = false,
		["side"] = "Horde",
	},
	[2422] = {
		useless = true,
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Night Fae",
		["defS"] = false,
		["ruRU"] = "Ночной народец",
	},
	[1711] = {
		["AddedInPatch"] = "6.0.1.18566",
		["enUS"] = "Steamwheedle Preservation Society",
		["Quartermaster"] = "88482 88493",
		["ruRU"] = "Археологическое общество Хитрой Шестеренки",
		["defS"] = false,
	},
	[1741] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Leorajh",
		["defS"] = false,
		["ruRU"] = "Леорадж",
	},
	[1847] = {
		["AddedInPatch"] = "6.2.0.20061",
		["enUS"] = "Hand of the Prophet",
		["side"] = "Alliance",
		["ruRU"] = "Длань Пророка",
		["defS"] = false,
		["expansion"] = "Fury of Hellfire",
	},
	[1733] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Delvar Ironfist",
		["defS"] = false,
		["ruRU"] = "Делвар Железный Кулак",
	},
	[2427] = {
		["AddedInPatch"] = "8.3.0.33062",
		["enUS"] = "Aqir Hatchling",
		["ruRU"] = "Молодой акир",
		["defS"] = false,
		["expansion"] = "Visions of N'Zoth",
	},
	[1216] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Shang Xi's Academy",
		["ruRU"] = "Академия Шан Си",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[369] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Gadgetzan",
		["defS"] = false,
		["ruRU"] = "Прибамбасск",
	},
	[1737] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Talonpriest Ishaal",
		["defS"] = false,
		["ruRU"] = "Жрец Когтя Ишааль",
	},
	[2431] = {
		["AddedInPatch"] = "8.3.0.33062",
		["enUS"] = "Owen Test",
		["ruRU"] = "Owen Test",
		["defS"] = false,
		["expansion"] = "Visions of N'Zoth",
	},
	[2432] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Ve'nari",
		["ruRU"] = "Ве'нари",
		["paragonQuest"] = 64267,
		["defS"] = false,
		["itemCache"] = 187029,
	},
	[1738] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Defender Illona",
		["defS"] = false,
		["ruRU"] = "Защитница Иллона",
	},
	[1739] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Vivianne",
		["defS"] = false,
		["ruRU"] = "Вивианна",
	},
	[1740] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Aeda Brightdawn",
		["defS"] = false,
		["ruRU"] = "Аеда Ясная Заря",
	},
	[1731] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Council of Exarchs",
		["Quartermaster"] = "85932",
		["ruRU"] = "Совет экзархов",
		["defS"] = false,
		["side"] = "Alliance",
	},
	[1815] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Gilnean Survivors",
		["defS"] = false,
		["ruRU"] = "Выжившие из Гилнеаса",
	},
	[1732] = {
		["AddedInPatch"] = "6.0.1.18663",
		["enUS"] = "Steamwheedle Draenor Expedition",
		["defS"] = false,
		["ruRU"] = "Дренорcкая Экспедиция Хитрой Шестеренки",
	},
	[2439] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Avowed",
		["ruRU"] = "Нераскаявшиеся",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2440] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Undying Army (Paragon)",
		["ruRU"] = "Неумирающая армия (Идеал)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2441] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Ascended (Paragon)",
		["ruRU"] = "Перерожденные (Идеал)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2442] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Court of Harvesters (Paragon)",
		["ruRU"] = "Двор Жнецов (Идеал)",
		["defS"] = false,
		["useless"] = "true",
	},
	[1848] = {
		["AddedInPatch"] = "6.2.0.20061",
		["enUS"] = "Vol'jin's Headhunters",
		["side"] = "Horde",
		["ruRU"] = "Охотники за головами",
		["defS"] = false,
		["expansion"] = "Fury of Hellfire",
	},
	[2444] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Wild Hunt (Paragon)",
		["ruRU"] = "Дикая Охота (Идеал)",
		["defS"] = false,
		["useless"] = "true",
	},
	[2445] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Ember Court",
		["ruRU"] = "Пепельный двор",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2446] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Baroness Vashj",
		["ruRU"] = "Баронесса Вайш",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2447] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Lady Moonberry",
		["ruRU"] = "Леди Лунная Ягода",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2448] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Mikanikos",
		["ruRU"] = "Миканикос",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2449] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "The Countess",
		["ruRU"] = "Графиня",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2450] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Alexandros Mograine",
		["ruRU"] = "Александрос Могрейн",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2451] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Hunt-Captain Korayn",
		["ruRU"] = "Капитан-егерь Корейн",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2452] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Polemarch Adrestes",
		["ruRU"] = "Полемарх Адрест",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2453] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Rendle and Cudgelface",
		["ruRU"] = "Рендл и Дуборыл",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2454] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Choofa",
		["ruRU"] = "Чуфа",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2455] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Cryptkeeper Kassir",
		["ruRU"] = "Хранитель склепа Каззир",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2456] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Droman Aliothe",
		["ruRU"] = "Дроман Алиот",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2457] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Grandmaster Vole",
		["ruRU"] = "Великий мастер Воул",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2458] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Kleia and Pelagos",
		["ruRU"] = "Клейя и Пелагий",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2459] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Sika",
		["ruRU"] = "Сика",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2460] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Stonehead",
		["ruRU"] = "Камнелоб",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2461] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Plague Deviser Marileth",
		["ruRU"] = "Изобретатель чумы Марилет",
		["icon"] = "CovenantChoice-Panel-Sigil-Venthyr",
		["defS"] = false,
	},
	[2462] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Stitchmasters",
		["ruRU"] = "Штопальщики",
		["icon"] = "CovenantChoice-Panel-Sigil-Necrolords",
		["defS"] = false,
	},
	[2463] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Marasmius",
		["ruRU"] = "Чесночник",
		["icon"] = "CovenantChoice-Panel-Sigil-NightFae",
		["defS"] = false,
	},
	[2464] = {
		["AddedInPatch"] = "9.0.1.36216",
		["enUS"] = "Court of Night",
		["ruRU"] = "Двор Ночи",
		["icon"] = "CovenantChoice-Panel-Sigil-NightFae",
		["defS"] = false,
	},
	[2465] = {
		["AddedInPatch"] = "9.0.2.36639",
		["enUS"] = "The Wild Hunt",
		["defS"] = false,
		["ruRU"] = "Дикая Охота",
		["paragonQuest"] = 61098,
		["itemCache"] = 180649,
		["icon"] = "CovenantChoice-Panel-Sigil-NightFae",
		["expansion"] = "Shadowlands",
	},
	[1849] = {
		["AddedInPatch"] = "6.2.0.20061",
		["enUS"] = "Order of the Awakened",
		["ruRU"] = "Орден Пробудившихся",
		["defS"] = false,
		["expansion"] = "Fury of Hellfire",
	},
	[1850] = {
		["AddedInPatch"] = "6.2.0.20061",
		["enUS"] = "The Saberstalkers",
		["ruRU"] = "Охотники за саблеронами",
		["defS"] = false,
		["expansion"] = "Fury of Hellfire",
	},
	[1861] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Arcane Thirst (Silgryn) DEPRECATED",
		["ruRU"] = "Arcane Thirst (Silgryn) DEPRECATED",
		["defS"] = false,
		["useless"] = "true",
	},
	[2469] = {
		["AddedInPatch"] = "9.2.0.42423",
		["enUS"] = "Fractal Lore",
		["ruRU"] = "Понимание фракталов",
		["defS"] = false,
		["expansion"] = "Eternity's End",
	},
	[2470] = {
		["AddedInPatch"] = "9.1.0.39185",
		["enUS"] = "Death's Advance",
		["ruRU"] = "Легион Смерти",
		["paragonQuest"] = 64012,
		["itemCache"] = 186650,
		["defS"] = false,
		["expansion"] = "Chains of Domination",
	},
	[2471] = {
		["AddedInPatch"] = "9.1.0.39185",
		["enUS"] = "Death's Advance (Paragon)",
		["ruRU"] = "Легион Смерти (идеал)",
		["expansion"] = "Chains of Domination",
		["defS"] = false,
		["useless"] = "true",
	},
	[2472] = {
		["AddedInPatch"] = "9.1.0.39185",
		["enUS"] = "The Archivists' Codex",
		["ruRU"] = "Кодекс архивариуса",
		["paragonQuest"] = 64266,
		["itemCache"] = 187028,
		["defS"] = false,
		["expansion"] = "Chains of Domination",
	},
	[2473] = {
		["AddedInPatch"] = "9.1.0.39185",
		["enUS"] = "The Archivists' Codex (Paragon)",
		["ruRU"] = "Кодекс архивариуса (идеал)",
		["expansion"] = "Chains of Domination",
		["defS"] = false,
		["useless"] = "true",
	},
	[2474] = {
		["AddedInPatch"] = "9.1.0.39185",
		["enUS"] = "Ve'nari (Paragon)",
		["ruRU"] = "Ве'нари (идеал)",
		["expansion"] = "Chains of Domination",
		["defS"] = false,
		["useless"] = "true",
	},
	[1900] = {
		["AddedInPatch"] = "7.0.1.20740",
		["enUS"] = "Court of Farondis",
		["ruRU"] = "Двор Фарондиса",
		["paragonQuest"] = 46745,
		["defS"] = false,
		["itemCache"] = 152102,
	},
	[1975] = {
		["AddedInPatch"] = "7.0.3.21287",
		["enUS"] = "Conjurer Margoss",
		["ruRU"] = "Кудесник Маргосс",
		["defS"] = false,
		["expansion"] = "Legion",
	},
	[749] = {
		["AddedInPatch"] = "1.0.0",
		["enUS"] = "Hydraxian Waterlords",
		["defS"] = false,
		["ruRU"] = "Гидраксианские Повелители Вод",
	},
	[2478] = {
		["AddedInPatch"] = "9.2.0.42423",
		["enUS"] = "The Enlightened",
		["ruRU"] = "Просветленные",
		["paragonQuest"] = 64867,
		["itemCache"] = 187780,
		["defS"] = false,
		["expansion"] = "Eternity's End",
	},
	[2479] = {
		["AddedInPatch"] = "9.2.0.42423",
		["enUS"] = "The Enlightened (Paragon)",
		["ruRU"] = "Просветленные (идеал)",
		["expansion"] = "Eternity's End",
		["defS"] = false,
		["useless"] = "true",
	},
	[1242] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Pearlfin Jinyu",
		["side"] = "Alliance",
		["ruRU"] = "Цзинь-юй Жемчужного Плавника",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2162] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Storm's Wake",
		["side"] = "Alliance",
		["ruRU"] = "Орден Возрождения Шторма",
		["paragonQuest"] = 54457,
		["itemCache"] = 166294,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2063] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Arne Test - Paragon Reputation Stormwind",
		["ruRU"] = "Arne Test - Paragon Reputation Stormwind",
		["defS"] = false,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2010] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Brawl'gar Arena (Season 3)",
		["side"] = "Horde",
		["ruRU"] = "Арена \"Морд'Бой\" (3-й сезон)",
		["defS"] = false,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2045] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Armies of Legionfall",
		["ruRU"] = "Армия погибели Легиона",
		["paragonQuest"] = 46777,
		["itemCache"] = 152108,
		["defS"] = false,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2011] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Bizmo's Brawlpub (Season 3)",
		["side"] = "Alliance",
		["ruRU"] = "Потасовочная \"У Бизмо\" (3-й сезон)",
		["defS"] = false,
		["expansion"] = "The Tomb of Sargeras",
	},
	[1245] = {
		["AddedInPatch"] = "5.0.4.15890",
		["enUS"] = "Mists of Pandaria",
		["ruRU"] = "Mists of Pandaria",
		["defS"] = false,
		["expansion"] = "Mists of Pandaria",
	},
	[2089] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "The Nightfallen (Paragon)",
		["ruRU"] = "Помраченные (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[2090] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "The Wardens (Paragon)",
		["ruRU"] = "Стражи (идеал)",
		["expansion"] = "The Tomb of Sargeras",
		["defS"] = false,
		["useless"] = "true",
	},
	[2100] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Corbyn",
		["ruRU"] = "Корбин",
		["defS"] = false,
		["icon"] = 1053367,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2101] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Sha'leth",
		["ruRU"] = "Ша'лет",
		["defS"] = false,
		["icon"] = 1053367,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2102] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Impus",
		["ruRU"] = "Бесс",
		["defS"] = false,
		["icon"] = 1053367,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2104] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Battle for Azeroth",
		["ruRU"] = "Battle for Azeroth",
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2156] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Talanji's Expedition",
		["side"] = "Horde",
		["ruRU"] = "Экспедиция Таланджи",
		["paragonQuest"] = 54460,
		["itemCache"] = 166282,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2157] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "The Honorbound",
		["side"] = "Horde",
		["ruRU"] = "Армия Чести",
		["paragonQuest"] = 54455,
		["itemCache"] = 166299,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2158] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Voldunai",
		["side"] = "Horde",
		["ruRU"] = "Жители Вол'дуна",
		["paragonQuest"] = 54461,
		["itemCache"] = 166290,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2159] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "7th Legion",
		["side"] = "Alliance",
		["ruRU"] = "7-й легион",
		["paragonQuest"] = 54454,
		["itemCache"] = 166300,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2160] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Proudmoore Admiralty",
		["side"] = "Alliance",
		["ruRU"] = "Адмиралтейство Праудмуров",
		["paragonQuest"] = 54458,
		["itemCache"] = 166295,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2161] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Order of Embers",
		["side"] = "Alliance",
		["ruRU"] = "Орден Пылающих Углей",
		["paragonQuest"] = 54456,
		["itemCache"] = 166297,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2018] = {
		["AddedInPatch"] = "7.2.0.23478",
		["enUS"] = "Talon's Vengeance",
		["ruRU"] = "Отмщение Когтя",
		["defS"] = false,
		["expansion"] = "The Tomb of Sargeras",
	},
	[2163] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Tortollan Seekers",
		["ruRU"] = "Тортолланские искатели",
		["paragonQuest"] = 54451,
		["itemCache"] = 166245,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2164] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Champions of Azeroth",
		["ruRU"] = "Защитники Азерот",
		["paragonQuest"] = 54453,
		["itemCache"] = 166298,
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},
	[2165] = {
		["AddedInPatch"] = "7.3.0.24614",
		["enUS"] = "Army of the Light",
		["ruRU"] = "Армия Света",
		["paragonQuest"] = 48977,
		["itemCache"] = 152923,
		["defS"] = false,
		["expansion"] = "Shadows of Argus",
	},
	[2503] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Maruuk Centaur",
		["defS"] = false,
		["ruRU"] = "Кентавры Маруук",
		["paragonQuest"] = 65606,
		["itemCache"] = 199474,
		["icon"] = "MajorFactions_Icons_Centaur512",
		["expansion"] = "Dragonflight",
	},
	[2504] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Maruuk Centaur (Paragon)",
		["ruRU"] = "Кентавры Маруук (идеал)",
		["expansion"] = "Dragonflight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2166] = {
		["AddedInPatch"] = "7.3.0.24614",
		["enUS"] = "Army of the Light (Paragon)",
		["ruRU"] = "Армия Света (идеал)",
		["expansion"] = "Shadows of Argus",
		["defS"] = false,
		["useless"] = "true",
	},
	[2506] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Dragonflight",
		["ruRU"] = "Dragonflight",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2507] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Dragonscale Expedition",
		["defS"] = false,
		["ruRU"] = "Драконья экспедиция",
		["paragonQuest"] = 66156,
		["itemCache"] = 199472,
		["icon"] = "MajorFactions_Icons_Expedition512",
		["expansion"] = "Dragonflight",
	},
	[2508] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Dragonscale Expedition (Paragon)",
		["ruRU"] = "Драконья экспедиция (идеал)",
		["expansion"] = "Dragonflight",
		["defS"] = false,
		["useless"] = "true",
	},
	[2509] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Clan Shikaar",
		["ruRU"] = "Клан Шикаар",
		["defS"] = false,
		["expansion"] = "Dragonflight",
	},
	[2510] = {
		["AddedInPatch"] = "10.0.0.46247",
		["enUS"] = "Valdrakken Accord",
		["defS"] = false,
		["ruRU"] = "Союз Вальдраккена",
		["paragonQuest"] = 71023,
		["itemCache"] = 199475,
		["icon"] = "MajorFactions_Icons_Valdrakken512",
		["expansion"] = "Dragonflight",
	},
	[2233] = {
		["AddedInPatch"] = "8.0.1.25902",
		["enUS"] = "Dino Training - Pterrodax",
		["side"] = "Horde",
		["ruRU"] = "Dino Training - Pterrodax",
		["defS"] = false,
		["expansion"] = "Battle for Azeroth",
	},

}
E.ALL_Reputations = {}
E.TBL_paragonQuests = {}
E.OctoTable_Reputations_Paragon_Data = {}
for reputationID, data in next, (E.OctoTable_Reputations_DB) do
	E.ALL_Reputations[reputationID] = true
	local paragonQuest = data.paragonQuest
	if paragonQuest then
		E.TBL_paragonQuests[paragonQuest] = true
		E.ALL_Quests[paragonQuest] = true
	end
	local itemCache = data.itemCache
	if itemCache then
		E.ALL_Items[itemCache] = true
	end
	if paragonQuest and itemCache then
		E.OctoTable_Reputations_Paragon_Data[paragonQuest] = {
			factionID = reputationID,
			cache = itemCache
		}
	end
end
-- local itemCache = E.OctoTable_Reputations_DB[id].itemCache
-- local paragonQuest = E.OctoTable_Reputations_DB[id].paragonQuest
-- E.cm.ListOfParagonQuests?????